### ISSUE TITLE
Is there any historical data for liquidations events?

### ISSUE THREAD

**Issue by AnCh7** [LittleLightLittleFire/REKT#2]
Thanks for the project!
Are u storing these events from bitmex somewhere? Can u plz share this history ?
I was also trying to download history from twitter, but unfortunately there is a limitation of 3200 tweets in the Twitter API.

**Comment by LittleLightLittleFire** [comment]
I have some logs but they don't go very far back.

**Comment by AnCh7** [comment]
Thanks a lot !
