### ISSUE TITLE
"Quantity" is confusing

### ISSUE THREAD

**Issue by matthewrudy** [LittleLightLittleFire/REKT#3]
Eg.

> Liquidated long on XBTUSD: Sell 3,722,291 @ 14130.5

Whenever I see this, I assume it means:

> 3,722,291 xbt @ $14,130.50 usd/xbt

But that would be $50 billion, which is obviously wrong.

So actually the quantity is the USD amount?

> $3,722,291 usd @ $14,130.50 usd/xbt

Maybe for clarity, just add a $ sign.

> Liquidated long on XBTUSD: Sell $3,722,291 @ $14130.5

Or just a USD suffix

> Liquidated long on XBTUSD: Sell 3,722,291 USD @ 14130.5

I don't know if you have any pairs that are not USD, but something like this would be clearer.

Thanks.

**Comment by LittleLightLittleFire** [comment]
Technically the unit is contracts. Each contract denoting one USD,

**Comment by Basdorsman** [comment]
I came here for this exact reason. It's not intuitive currently. I suggest listing units of cryptocurrency in brackets specifically for  crypto/USD pairs like so `35000 (1 BTC) @ 35000$`

**Comment by LittleLightLittleFire** [comment]
This was really hard but it really needed to get fixed for USDT linear contracts.
Fixed with https://github.com/LittleLightLittleFire/REKT/commit/22b3333cf8b0b95b19b8ff83c8bc69ee5ec55fed
